"""retirando animal

Revision ID: 4a7d9e588c86
Revises: 808ab481f595
Create Date: 2022-04-16 22:36:58.842920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7d9e588c86'
down_revision = '808ab481f595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Animal_id', table_name='Animal')
    op.drop_table('Animal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Animal',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Animal_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sexo', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('raca', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('idade', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('vacinacao', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('validacao_vacina', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], name='Animal_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='Animal_pkey')
    )
    op.create_index('ix_Animal_id', 'Animal', ['id'], unique=False)
    # ### end Alembic commands ###
