"""alterando coluna email

Revision ID: 72b4f2d3c94d
Revises: f0b5014704f5
Create Date: 2022-04-23 22:35:47.813915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b4f2d3c94d'
down_revision = 'f0b5014704f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Usuario_email_key', 'Usuario', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Usuario_email_key', 'Usuario', ['email'])
    # ### end Alembic commands ###
