"""email unico2

Revision ID: 780f849aaff9
Revises: 9b488d175157
Create Date: 2022-04-16 23:05:26.348801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780f849aaff9'
down_revision = '9b488d175157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Usuario_nome_key', 'Usuario', type_='unique')
    op.create_unique_constraint(None, 'Usuario', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Usuario', type_='unique')
    op.create_unique_constraint('Usuario_nome_key', 'Usuario', ['nome'])
    # ### end Alembic commands ###
