"""email unico

Revision ID: 9b488d175157
Revises: 4a7d9e588c86
Create Date: 2022-04-16 22:59:39.561190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b488d175157'
down_revision = '4a7d9e588c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Usuario', ['nome'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Usuario', type_='unique')
    # ### end Alembic commands ###
