"""alterando coluna senha

Revision ID: af7bb6519258
Revises: 780f849aaff9
Create Date: 2022-04-23 22:16:00.610366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7bb6519258'
down_revision = '780f849aaff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
