"""alterando coluna senha2

Revision ID: ec1b5b250f1e
Revises: 2f5f65c8d049
Create Date: 2022-04-23 22:30:18.902149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1b5b250f1e'
down_revision = '2f5f65c8d049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
